
package com.bytekast.netsuite.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-18T08:45:21.247-07:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "exceededConcurrentRequestLimitFault", targetNamespace = "urn:faults_2017_1.platform.webservices.netsuite.com")
public class ExceededConcurrentRequestLimitFault_Exception extends Exception {
    
    private com.bytekast.netsuite.client.ExceededConcurrentRequestLimitFault exceededConcurrentRequestLimitFault;

    public ExceededConcurrentRequestLimitFault_Exception() {
        super();
    }
    
    public ExceededConcurrentRequestLimitFault_Exception(String message) {
        super(message);
    }
    
    public ExceededConcurrentRequestLimitFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceededConcurrentRequestLimitFault_Exception(String message, com.bytekast.netsuite.client.ExceededConcurrentRequestLimitFault exceededConcurrentRequestLimitFault) {
        super(message);
        this.exceededConcurrentRequestLimitFault = exceededConcurrentRequestLimitFault;
    }

    public ExceededConcurrentRequestLimitFault_Exception(String message, com.bytekast.netsuite.client.ExceededConcurrentRequestLimitFault exceededConcurrentRequestLimitFault, Throwable cause) {
        super(message, cause);
        this.exceededConcurrentRequestLimitFault = exceededConcurrentRequestLimitFault;
    }

    public com.bytekast.netsuite.client.ExceededConcurrentRequestLimitFault getFaultInfo() {
        return this.exceededConcurrentRequestLimitFault;
    }
}
