
package com.bytekast.netsuite.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-18T08:45:21.343-07:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "invalidAccountFault", targetNamespace = "urn:faults_2017_1.platform.webservices.netsuite.com")
public class InvalidAccountFault_Exception extends Exception {
    
    private com.bytekast.netsuite.client.InvalidAccountFault invalidAccountFault;

    public InvalidAccountFault_Exception() {
        super();
    }
    
    public InvalidAccountFault_Exception(String message) {
        super(message);
    }
    
    public InvalidAccountFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidAccountFault_Exception(String message, com.bytekast.netsuite.client.InvalidAccountFault invalidAccountFault) {
        super(message);
        this.invalidAccountFault = invalidAccountFault;
    }

    public InvalidAccountFault_Exception(String message, com.bytekast.netsuite.client.InvalidAccountFault invalidAccountFault, Throwable cause) {
        super(message, cause);
        this.invalidAccountFault = invalidAccountFault;
    }

    public com.bytekast.netsuite.client.InvalidAccountFault getFaultInfo() {
        return this.invalidAccountFault;
    }
}
