
package com.bytekast.netsuite.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-18T08:45:21.309-07:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "invalidSessionFault", targetNamespace = "urn:faults_2017_1.platform.webservices.netsuite.com")
public class InvalidSessionFault_Exception extends Exception {
    
    private com.bytekast.netsuite.client.InvalidSessionFault invalidSessionFault;

    public InvalidSessionFault_Exception() {
        super();
    }
    
    public InvalidSessionFault_Exception(String message) {
        super(message);
    }
    
    public InvalidSessionFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidSessionFault_Exception(String message, com.bytekast.netsuite.client.InvalidSessionFault invalidSessionFault) {
        super(message);
        this.invalidSessionFault = invalidSessionFault;
    }

    public InvalidSessionFault_Exception(String message, com.bytekast.netsuite.client.InvalidSessionFault invalidSessionFault, Throwable cause) {
        super(message, cause);
        this.invalidSessionFault = invalidSessionFault;
    }

    public com.bytekast.netsuite.client.InvalidSessionFault getFaultInfo() {
        return this.invalidSessionFault;
    }
}
